### ISSUE TITLE
please do trackmania sunrise next

### ISSUE THREAD

**Issue by co5mo** [WIFIDarthMaul/Peter-Jackson-s-King-Kong-Signature-Edition-Fix#2]
hi is it possible to do trackmania sunrise extreme next?

**Comment by WIFIDarthMaul** [comment]
I'm assuming you want it to run on Windows 10? If so, someone has already made a fix for that: https://www.youtube.com/watch?v=18jLklAE7q0

**Comment by co5mo** [comment]
oh didn't know about that thanks i think it broke win least time i tried that
